## Time Series Feature Extraction and Visualisation Application
***

### What is this application?

This application automatically takes an input dataset containing multiple time series, processes it, calculates a set of time-series features, and produces a range of interactive visualisations and statistical analyses for the extracted features all within your web browser. If your data contains a class label vector (i.e., group labels), this application also produces automated time-series classification using a broad range of machine learning algorithms with the calculated feature matrix as an input.

The backbone of the application is the `R` package [`theft`](https://github.com/hendersontrent/theft) - Tools for Handling Extraction of Features from Time series. This application enables researchers unfamiliar with `R` or code to explore the vast functionality of `theft` and feature-based time-series analysis in general in their web browser. Note that not all of the power of `theft` is currently in this application --- the three Python feature sets (`tsfresh`, `TSFEL`, and `Kats`) which `theft` provides access to are currently not supported yet. Including these feature sets is an active area of development for this application.

### How do I use it?

The application only requires a time-series dataset to be uploaded to get started. Navigate to the homepage and upload your time series dataset. Support for more input formats are being continuously added. Please check back soon for more options if you data format is not currently accepted, otherwise, please convert to an accepted format in the meantime.

### Who made it?

This application was developed by [Trent Henderson](https://twitter.com/trentlikesstats) -- a PhD student in the [Dynamics and Neural Systems Group](https://dynamicsandneuralsystems.github.io) in the School of Physics at The University of Sydney. Please send any questions to Trent via [email](then6675@sydney.edu.au). If you identify an issue with the application itself, or want to contribute, please log an issue or pull request at the [GitHub repository](https://github.com/hendersontrent/theft-webtool/issues).

### Where can I read more?

There are numerous resources associated with this application. Some of these are linked below.

* T. Henderson and B. D. Fulcher. [An Empirical Evaluation of Time-Series Feature Sets](https://ieeexplore.ieee.org/document/9679937). 2021 International Conference on Data Mining Workshops (ICDMW), (2022).
* [`hctsa`](https://github.com/benfulcher/hctsa) software toolbox for MATLAB
* B.D. Fulcher and N.S. Jones. [hctsa: A computational framework for automated time-series phenotyping using massive feature extraction](https://www.cell.com/cell-systems/fulltext/S2405-4712(17)30438-6). Cell Systems 5, 527 (2017).
* B.D. Fulcher, M.A. Little, N.S. Jones. [Highly comparative time-series analysis: the empirical structure of time series and their methods](https://royalsocietypublishing.org/doi/full/10.1098/rsif.2013.0048). J. Roy. Soc. Interface 10, 83 (2013).
* [`catch22`](https://github.com/chlubba/catch22) software toolbox in C
* Lubba, C. H. et al. [catch22: CAnonical Time-series CHaracteristics](https://link.springer.com/article/10.1007/s10618-019-00647-x). Data Mining and Knowledge Discovery, 33 (2019)
* [Rcatch22](https://github.com/hendersontrent/Rcatch22) software toolbox - Trent Henderson (2021). Rcatch22: Calculation of 22 CAnonical Time-Series CHaracteristics. R package version 0.1.12. https://CRAN.R-project.org/package=Rcatch22
* [`feasts`](https://feasts.tidyverts.org) software toolbox - Mitchell O'Hara-Wild, Rob Hyndman and Earo Wang (2021). feasts: Feature Extraction and Statistics for Time Series. R package version 0.2.1. https://CRAN.R-project.org/package=feasts
* [`tsfeatures`](https://pkg.robjhyndman.com/tsfeatures/) software toolbox - Rob Hyndman, Yanfei Kang, Pablo Montero-Manso, Thiyanga Talagala, Earo Wang, Yangzhuoran Yang and Mitchell O'Hara-Wild (2020). tsfeatures: Time Series Feature Extraction. R package version 1.0.2. https://CRAN.R-project.org/package=tsfeatures
